{
 "title": "Network Latency Tiles",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (Points Of Interest)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"blackbox\", phase=\"rtt\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency (GSL Networks)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"gsl\", phase=\"rtt\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency (Alexa Top 50)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"alexatopsites\", phase=\"rtt\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}